name: "Build and Publish Docker image"

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master

jobs:
  docker:
    name: Build and Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - service_name: "linux-amd64"
            platform: linux/amd64
          - service_name: "linux-arm64"
            platform: linux/arm64
    steps:
      - name: Check out the repo
        uses: actions/checkout@main

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@master
        with:
          images: ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@master
        with:
          platforms: ${{ matrix.platform }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@master

      - name: Log in to Docker Hub
        uses: docker/login-action@master
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@master
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ github.repository }}:latest
          labels: ${{ steps.meta.outputs.labels }}
